### ISSUE TITLE
Bug with "BlargleBrew" mod item

### ISSUE THREAD

**Issue by UnderwearApp** [Phelms215/RealisticOrdering#1]
Not sure if you prefer bugs here or on Steam, or if you're even planning to update this mod.

There is an issue with at least one of the items in the Beer mod. If a customer orders a "WhO" or "Wheat with Orange" they won't accept the order when this mod is turned on. I tried cycling the mod while the order was active and the order changed when this was disabled. I can confirm they accept the Wheat with Orange when this mod is not active.

For what it's worth I also had one customer come in, sit, think, then leave. It was clear weather on Day 6. I like this feature personally if it's not a bug. Would be interesting to have some people sit down, decide they don't want anything then leave.

Edit: The same issue occurs using Coffee as a starter main. The picture for their order appears, but not the colorblind info, and they can't accept the order. Turning this mod off fixes the issue. I'm not sure if the coffee is vanilla or from a mod. If modded it would have to be "Mini Cafe" I think.

Cheers!

**Comment by Phelms215** [comment]
Known issue which should be addressed in an update planned for early April
